apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-auth-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: med-auth-ms
  template:
    metadata:
      labels:
        app: med-auth-ms
    spec:
      containers:
      - name: med-auth-ms
        image: 975050002971.dkr.ecr.us-east-1.amazonaws.com/med-auth-ms:latest
        ports:
        - containerPort: 3004
        livenessProbe:
          httpGet:
            path: /
            port: 3004
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 3004
          initialDelaySeconds: 15
        resources:
          requests:
            cpu: 10m
        imagePullPolicy: Always        

---
apiVersion: v1
kind: Service
metadata:
  name: svc-med-auth-ms
spec:
  type: LoadBalancer
  selector:
    app: med-auth-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
